Update CICD_PROJECTS

diff --git a/CICD_PROJECTS b/CICD_PROJECTS
--- a/CICD_PROJECTS
+++ b/CICD_PROJECTS
@@ -2721,7 +2721,7 @@ v1beta1.metrics.k8s.io   Available
 
 github action yaml file
 
-name: Enterprise autoscaling Pipeline (ECR + EKS)
+name: Enterprise DevSecOps AutoScaling Pipeline
 
 on:
   workflow_dispatch:
@@ -2735,7 +2735,7 @@ on:
           - production
 
 jobs:
-  devsecops:
+  autoscaling:
     runs-on: self-hosted
 
     environment: ${{ inputs.target_env }}
@@ -2745,7 +2745,12 @@ jobs:
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
       AWS_REGION: ${{ secrets.AWS_REGION }}
+
       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
 
@@ -2754,7 +2759,7 @@ jobs:
     steps:
 
       #########################################################
-      # STEP 1 - CHECKOUT CODE
+      # STEP 1 - CHECKOUT SOURCE CODE
       #########################################################
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -2769,18 +2774,7 @@ jobs:
           java-version: 17
 
       #########################################################
-      # STEP 3 - CACHE MAVEN DEPENDENCIES
-      #########################################################
-      - name: Cache Maven Dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            maven-${{ runner.os }}-
-
-      #########################################################
-      # STEP 4 - SET VERSION
+      # STEP 3 - SET VERSION
       #########################################################
       - name: Set Version
         run: |
@@ -2790,7 +2784,7 @@ jobs:
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       #########################################################
-      # STEP 5 - VERIFY TOOLS
+      # STEP 4 - VERIFY TOOLS
       #########################################################
       - name: Verify Installed Tools
         run: |
@@ -2801,12 +2795,14 @@ jobs:
 
           docker --version
 
+          docker-compose --version
+
           kubectl version --client
 
           aws --version
 
       #########################################################
-      # STEP 6 - MAVEN BUILD
+      # STEP 5 - MAVEN BUILD
       #########################################################
       - name: Maven Build
         run: |
@@ -2814,7 +2810,7 @@ jobs:
           mvn clean package -DskipTests
 
       #########################################################
-      # STEP 7 - SONARQUBE SCAN
+      # STEP 6 - SONARQUBE SCAN
       #########################################################
       - name: SonarQube Scan
         run: |
@@ -2827,38 +2823,25 @@ jobs:
             -Dsonar.qualitygate.wait=true
 
       #########################################################
-      # STEP 8 - TRIVY FILE SYSTEM SCAN
+      # STEP 7 - TRIVY FILE SYSTEM SCAN
       #########################################################
-      - name: Trivy File System Scan
+      - name: Trivy FS Scan
         run: |
 
-          trivy fs . > trivyfs-report.txt
+          trivy fs . > trivyfs.txt
 
       #########################################################
-      # STEP 9 - CLEAN DOCKER CACHE
-      #########################################################
-      - name: Clean Docker Cache
-        run: |
-
-          docker builder prune -af || true
-
-          docker system prune -af || true
-
-      #########################################################
-      # STEP 10 - BUILD DOCKER IMAGE
+      # STEP 8 - BUILD DOCKER IMAGE
       #########################################################
       - name: Build Docker Image
         run: |
 
-          docker build \
-            --pull \
-            --no-cache \
-            -t employees-app:${VERSION} .
+          docker build -t employees-app:${VERSION} .
 
           docker tag employees-app:${VERSION} employees-app:latest
 
       #########################################################
-      # STEP 11 - TRIVY IMAGE SCAN
+      # STEP 9 - TRIVY IMAGE SCAN
       #########################################################
       - name: Trivy Image Scan
         run: |
@@ -2866,17 +2849,19 @@ jobs:
           trivy image employees-app:${VERSION}
 
       #########################################################
-      # STEP 12 - CONFIGURE AWS CREDENTIALS
+      # STEP 10 - CONFIGURE AWS CREDENTIALS
       #########################################################
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
           aws-region: ${{ secrets.AWS_REGION }}
 
       #########################################################
-      # STEP 13 - VERIFY AWS LOGIN
+      # STEP 11 - VERIFY AWS LOGIN
       #########################################################
       - name: Verify AWS Identity
         run: |
@@ -2884,21 +2869,21 @@ jobs:
           aws sts get-caller-identity
 
       #########################################################
-      # STEP 14 - LOGIN TO ECR
+      # STEP 12 - LOGIN TO ECR
       #########################################################
-      - name: Login to Amazon ECR
+      - name: Login to ECR
         run: |
 
           aws ecr get-login-password --region $AWS_REGION \
           | docker login \
-            --username AWS \
-            --password-stdin \
-            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
+          --username AWS \
+          --password-stdin \
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
 
       #########################################################
-      # STEP 15 - TAG IMAGE FOR ECR
+      # STEP 13 - TAG IMAGE FOR ECR
       #########################################################
-      - name: Tag Docker Image
+      - name: Tag Image for ECR
         run: |
 
           docker tag employees-app:${VERSION} \
@@ -2908,19 +2893,45 @@ jobs:
           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
 
       #########################################################
-      # STEP 16 - PUSH IMAGE TO ECR
+      # STEP 14 - PUSH IMAGE TO ECR
       #########################################################
       - name: Push Image to ECR
         run: |
 
           docker push \
-            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}
 
           docker push \
-            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
 
       #########################################################
-      # STEP 17 - CONFIGURE KUBECONFIG
+      # STEP 15 - UPDATE DOCKER COMPOSE IMAGE
+      #########################################################
+      #- name: Update Docker Compose Image
+       # run: |
+
+        #  sed -i "s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}|g" docker-compose.yml
+
+      #########################################################
+      # STEP 16 - LOCAL DOCKER COMPOSE DEPLOY
+      #########################################################
+      - name: Deploy Containers
+        run: |
+
+          docker-compose down || true
+
+          docker-compose up -d
+
+      #########################################################
+      # STEP 17 - VERIFY LOCAL CONTAINERS
+      #########################################################
+      - name: Verify Running Containers
+        run: |
+
+          docker ps
+
+      #########################################################
+      # STEP 18 - CONFIGURE KUBECONFIG
       #########################################################
       - name: Configure kubeconfig
         run: |
@@ -2930,7 +2941,7 @@ jobs:
             --name ${CLUSTER_NAME}
 
       #########################################################
-      # STEP 18 - VERIFY EKS CLUSTER
+      # STEP 19 - VERIFY EKS CLUSTER
       #########################################################
       - name: Verify EKS Cluster
         run: |
@@ -2938,7 +2949,15 @@ jobs:
           kubectl get nodes
 
       #########################################################
-      # STEP 19 - CREATE NAMESPACE
+      # STEP 20 - VERIFY METRICS SERVER
+      #########################################################
+      - name: Verify Metrics Server
+        run: |
+
+          kubectl get apiservices | grep metrics || true
+
+      #########################################################
+      # STEP 21 - CREATE NAMESPACE
       #########################################################
       - name: Create Namespace
         run: |
@@ -2947,46 +2966,43 @@ jobs:
           kubectl create namespace vk67220-ns
 
       #########################################################
-      # STEP 20 - DEPLOY KUBERNETES YAML FILES
+      # STEP 23 - DEPLOY AUTOSCALING YAML FILES
       #########################################################
-      - name: Deploy Kubernetes Resources
+      - name: Deploy AutoScaling Resources
         run: |
 
-          kubectl apply -f k8s/
+          kubectl apply -f autoscaling/
 
       #########################################################
-      # STEP 21 - RESTART DEPLOYMENT
+      # STEP 24 - VERIFY HPA
       #########################################################
-      - name: Restart Deployment
+      - name: Verify HPA
         run: |
 
-          kubectl rollout restart deployment/employee-app \
+          kubectl get hpa -n vk67220-ns
+
+          kubectl describe hpa employee-app-hpa \
             -n vk67220-ns
 
       #########################################################
-      # STEP 22 - WAIT FOR ROLLOUT
+      # STEP 25 - VERIFY DEPLOYMENT
       #########################################################
-      - name: Wait for Rollout
+      - name: Verify Deployment
         run: |
 
-          kubectl rollout status deployment/employee-app \
-            -n vk67220-ns \
-            --timeout=300s
+          kubectl get deployment \
+            -n vk67220-ns
 
       #########################################################
-      # STEP 23 - VERIFY KUBERNETES RESOURCES
+      # STEP 26 - VERIFY PODS
       #########################################################
-      - name: Verify Kubernetes Resources
+      - name: Verify Pods
         run: |
 
-          kubectl get all -n vk67220-ns
-
-          kubectl get pvc -n vk67220-ns
-
-          kubectl get storageclass
+          kubectl get pods -n vk67220-ns
 
       #########################################################
-      # STEP 24 - VERIFY SERVICES
+      # STEP 27 - VERIFY SERVICES
       #########################################################
       - name: Verify Services
         run: |
@@ -2994,20 +3010,48 @@ jobs:
           kubectl get svc -n vk67220-ns
 
       #########################################################
-      # STEP 25 - VERIFY POD METRICS
+      # STEP 28 - VERIFY STATEFULSET
+      #########################################################
+      - name: Verify StatefulSet
+        run: |
+
+          kubectl get statefulset -n vk67220-ns
+
+      #########################################################
+      # STEP 29 - VERIFY PVC
+      #########################################################
+      - name: Verify PVC
+        run: |
+
+          kubectl get pvc -n vk67220-ns
+
+      #########################################################
+      # STEP 30 - VERIFY METRICS
       #########################################################
       - name: Verify Metrics
         run: |
 
           kubectl top pods -n vk67220-ns || true
 
+          kubectl top nodes || true
+
       #########################################################
-      # STEP 26 - CLEANUP OLD DOCKER IMAGES
+      # STEP 31 - VERIFY ROLLOUT STATUS
+      #########################################################
+      - name: Verify Rollout
+        run: |
+
+          kubectl rollout status deployment/employee-app \
+            -n vk67220-ns \
+            --timeout=300s
+
+      #########################################################
+      # STEP 32 - CLEANUP OLD DOCKER IMAGES
       #########################################################
       - name: Cleanup Docker Images
         run: |
 
-          docker image prune -af
+          docker image prune -a -f
 
 To test HPA follow below steps 
 
